### PR TITLE
Improve Stmt and Computation == operators

### PR DESCRIPTION
**Pull request by riftEmber**

### CODE REVIEW

**Review by macdonaldlowe — COMMENTED** [review]
I'm not sure I'd be the best to review this as I've only dabbled in the computation infrastructure. However, these changes make sense.  With these changes can you try make tutorial and then in the build/bin/tutorial ./geoac_codegen_driver ? I'm worried the changes might break something unforeseen

**Comment by riftEmber** [comment]
It seems to have compiled and run fine. I basically was just wondering if the new checks I added in the equality operator for Stmt make sense to compare, like comparing the "debug" and those other new variables

**Comment by macdonaldlowe** [comment]
The only comparison I would leave off is the debug one actually, because debug is used as a tool to find where an error is coming from it doesn't actually impact the execution of the code in any way. The rest look good.

**Review by macdonaldlowe — APPROVED** [review]
Just leave off the debug comparison, the rest look good.

**Comment by riftEmber** [comment]
Makes sense, I'll remove that one and merge

**Pull request merged**
